from pathlib import Path
root=Path('native')
# Version
p=root/'app/build.gradle.kts'; s=p.read_text(); s=s.replace('versionCode = 16','versionCode = 17').replace('versionName = "1.6.0"','versionName = "1.6.1"'); p.write_text(s)
(root/'app/src/main/assets/irs_spect_release.json').write_text('{"package_id":"ir.dinavo.fraudwatch","version_code":17,"version_name":"1.6.1"}\n')
p=root/'app/src/main/java/ir/dinavo/fraudwatch/MainActivity.java'; s=p.read_text(); s=s.replace('static final int APP_VERSION_CODE=16;','static final int APP_VERSION_CODE=17;').replace('static final String APP_VERSION_NAME="1.6.0";','static final String APP_VERSION_NAME="1.6.1";')
s=s.replace('logo.setImageResource(R.drawable.ic_splash);','logo.setImageResource(R.drawable.irs_spect_logo);')
old='TextView avatar=UiKit.title(this,"IRS",11);avatar.setGravity(Gravity.CENTER);avatar.setTextColor(UiKit.ACCENT);avatar.setBackground(UiKit.round(UiKit.withAlpha(UiKit.ACCENT,18),14,UiKit.withAlpha(UiKit.ACCENT,80),1,this));bar.addView(avatar,new LinearLayout.LayoutParams(UiKit.dp(this,44),UiKit.dp(this,44)));return bar;'
new='ImageView avatar=new ImageView(this);avatar.setImageResource(R.drawable.irs_spect_logo);avatar.setScaleType(ImageView.ScaleType.CENTER_CROP);avatar.setPadding(UiKit.dp(this,4),UiKit.dp(this,4),UiKit.dp(this,4),UiKit.dp(this,4));avatar.setBackground(UiKit.round(UiKit.withAlpha(UiKit.ACCENT,12),14,UiKit.withAlpha(UiKit.ACCENT,70),1,this));bar.addView(avatar,new LinearLayout.LayoutParams(UiKit.dp(this,44),UiKit.dp(this,44)));return bar;'
if old in s:s=s.replace(old,new)
s=s.replace('case"multi":multi("");break;case"multigroup":multiGroup(page.label);break;case"multipair":multiPair(page.label);break;', 'case"multi":multi("");break;case"multigroup":multiGroup(page.label);break;case"multiplayer":multiPlayer(page.id,page.label);break;case"multipair":multiPair(page.label);break;')
s=s.replace('c.setOnClickListener(v->load(new Page("player",pid,pn),true));', 'c.setOnClickListener(v->load(new Page("multiplayer",pid,pn),true));')
# Keep ordinary search/suspicious-player cards on the normal player profile.
s=s.replace('c.setOnClickListener(v->load(new Page("multiplayer",pid,pn),true));UiKit.pressMotion(c,this);UiKit.enter(c,order);return c;}', 'c.setOnClickListener(v->load(new Page("player",pid,pn),true));UiKit.pressMotion(c,this);UiKit.enter(c,order);return c;}',1)
needle='    private void multiPair(String label)'
if 'private void multiPlayer(' not in s:
    insert='''    private void multiPlayer(int id,String fallback){header(fallback.isEmpty()?"جزئیات مولتی‌اکانت":fallback,"شبکه IP مشترک و تراکنش‌ها",true);swap(loading());api.get("/multi/player/"+id,r->runOnUiThread(()->{if(!"multiplayer".equals(currentPage.type)||currentPage.id!=id)return;if(!r.ok()){swap(error(r.message("جزئیات مولتی‌اکانت دریافت نشد."),()->multiPlayer(id,fallback)));return;}JSONObject p=r.json.optJSONObject("player");if(p==null){swap(error("بازیکن پیدا نشد.",null));return;}header(p.optString("player_name",fallback),"Player ID "+p.optInt("player_id"),true);LinearLayout b=body();LinearLayout hero=UiKit.card(this);hero.addView(UiKit.title(this,p.optString("player_name","—"),20));hero.addView(infoRow("ریسک",String.valueOf(p.optInt("risk_score",0))));hero.addView(infoRow("آخرین IP",p.optString("last_known_ip","—")));hero.addView(infoRow("اولین مشاهده",p.optString("first_seen_at","—")));hero.addView(infoRow("آخرین مشاهده",p.optString("last_seen_at","—")));b.addView(hero);JSONArray clusters=r.json.optJSONArray("clusters");if(clusters!=null&&clusters.length()>0){sectionTitle(b,"IPهای مشترک","",null);for(int i=0;i<clusters.length();i++){JSONObject g=clusters.optJSONObject(i);if(g==null)continue;LinearLayout c=UiKit.card(this);String ip=g.optString("ip",g.optString("shared_ip","—"));c.addView(UiKit.title(this,ip,14));c.addView(UiKit.text(this,g.optInt("account_count",0)+" اکانت · "+g.optInt("transaction_count",0)+" تراکنش",11,UiKit.MUTED));String finalIp=ip;c.setOnClickListener(v->load(new Page("multigroup",0,finalIp),true));UiKit.pressMotion(c,this);b.addView(c,cardParams(i));}}JSONArray accounts=r.json.optJSONArray("accounts");sectionTitle(b,"اکانت‌های مرتبط","",null);if(accounts!=null)for(int i=0;i<accounts.length();i++){JSONObject a=accounts.optJSONObject(i);if(a==null)continue;LinearLayout c=UiKit.card(this);c.addView(UiKit.title(this,a.optString("player_name","—")+" ["+a.optInt("player_id")+"]",14));c.addView(UiKit.text(this,a.optInt("shared_ip_count",0)+" IP مشترک · "+a.optInt("transaction_count",0)+" تراکنش · "+formatMoney(a.optString("total_amount","0")),11,UiKit.MUTED));int other=a.optInt("player_id");String label=id+"|"+other+"|"+p.optString("player_name","")+"|"+a.optString("player_name","");c.setOnClickListener(v->load(new Page("multipair",0,label),true));UiKit.pressMotion(c,this);b.addView(c,cardParams(i));}if(accounts==null||accounts.length()==0)b.addView(empty("اکانت مرتبطی پیدا نشد."));Button profile=UiKit.button(this,"باز کردن پروفایل کامل بازیکن",false);LinearLayout.LayoutParams pp=new LinearLayout.LayoutParams(-1,UiKit.dp(this,48));pp.topMargin=UiKit.dp(this,10);b.addView(profile,pp);profile.setOnClickListener(v->load(new Page("player",id,p.optString("player_name",fallback)),true));swap(scroll(b));}));}\n\n'''
    s=s.replace(needle,insert+needle)
s=s.replace('if(id==EditorInfo.IME_ACTION_SEARCH){run.run();return true;}', 'if(id==EditorInfo.IME_ACTION_SEARCH){hideKeyboard(q);run.run();return true;}')
s=s.replace('if(id==EditorInfo.IME_ACTION_SEARCH){incidents(risk,search.getText().toString().trim(),archived);return true;}', 'if(id==EditorInfo.IME_ACTION_SEARCH){hideKeyboard(search);incidents(risk,search.getText().toString().trim(),archived);return true;}')
s=s.replace('if(id==EditorInfo.IME_ACTION_SEARCH){suspiciousPlayers(search.getText().toString().trim());return true;}', 'if(id==EditorInfo.IME_ACTION_SEARCH){hideKeyboard(search);suspiciousPlayers(search.getText().toString().trim());return true;}')
s=s.replace('if(id==EditorInfo.IME_ACTION_SEARCH){multi(search.getText().toString().trim());return true;}', 'if(id==EditorInfo.IME_ACTION_SEARCH){hideKeyboard(search);multi(search.getText().toString().trim());return true;}')
oldpush='EditText pushTitle=UiKit.input(this,"عنوان اعلان",false),pushText=UiKit.input(this,"متن اعلان",false),audience=UiKit.input(this,"گیرنده: all یا username",false),hours=UiKit.input(this,"اعتبار (ساعت)",false);audience.setText("all");hours.setText("168");b.addView(pushTitle,new LinearLayout.LayoutParams(-1,UiKit.dp(this,50)));b.addView(pushText,ip);b.addView(audience,ip);b.addView(hours,ip);Button push=UiKit.button(this,"ارسال Push",false);b.addView(push,pub);push.setOnClickListener(v->api.post("/admin/broadcast",json("title",pushTitle.getText().toString().trim(),"message",pushText.getText().toString().trim(),"audience",audience.getText().toString().trim(),"target","dashboard","hours",hours.getText().toString().trim()),res->runOnUiThread(()->{Toast.makeText(this,res.ok()?"اعلان ارسال شد.":res.message("ارسال نشد."),Toast.LENGTH_LONG).show();if(res.ok())appManager();})));'
newpush='EditText pushTitle=UiKit.input(this,"عنوان اعلان",false),pushText=UiKit.input(this,"متن اعلان",false),audience=UiKit.input(this,"گیرنده: all یا username",false),hours=UiKit.input(this,"اعتبار (ساعت)",false);audience.setText("all");hours.setText("168");Spinner pushTarget=spinner(new String[]{"داشبورد","موارد مشکوک"});b.addView(pushTitle,new LinearLayout.LayoutParams(-1,UiKit.dp(this,50)));b.addView(pushText,ip);b.addView(audience,ip);b.addView(hours,ip);LinearLayout.LayoutParams ptp=new LinearLayout.LayoutParams(-1,UiKit.dp(this,50));ptp.topMargin=UiKit.dp(this,8);b.addView(pushTarget,ptp);Button push=UiKit.button(this,"ارسال Push",false);b.addView(push,pub);push.setOnClickListener(v->api.post("/admin/broadcast",json("title",pushTitle.getText().toString().trim(),"message",pushText.getText().toString().trim(),"audience",audience.getText().toString().trim(),"target",pushTarget.getSelectedItemPosition()==1?"incidents":"dashboard","hours",hours.getText().toString().trim()),res->runOnUiThread(()->{Toast.makeText(this,res.ok()?"اعلان ارسال شد.":res.message("ارسال نشد."),Toast.LENGTH_LONG).show();if(res.ok())appManager();})));'
s=s.replace(oldpush,newpush)
needle2='    private void requestNotificationPermission()'
if 'private void hideKeyboard(View view)' not in s:
    s=s.replace(needle2,'    private void hideKeyboard(View view){try{android.view.inputmethod.InputMethodManager imm=(android.view.inputmethod.InputMethodManager)getSystemService(Context.INPUT_METHOD_SERVICE);if(imm!=null)imm.hideSoftInputFromWindow(view.getWindowToken(),0);view.clearFocus();}catch(Exception ignored){}}\n'+needle2)
p.write_text(s)
# Ui kit polish
p=root/'app/src/main/java/ir/dinavo/fraudwatch/UiKit.java'; u=p.read_text()
u=u.replace('v.setTextDirection(View.TEXT_DIRECTION_RTL);v.setLineSpacing(0,1.15f);', 'v.setTextDirection(View.TEXT_DIRECTION_FIRST_STRONG);v.setLineSpacing(0,1.18f);v.setIncludeFontPadding(false);')
old='b.setBackground(round(primary?ACCENT:SURFACE_2,15,primary?ACCENT:BORDER,1,c));pressMotion(b,c);return b;'
new='GradientDrawable d;if(primary){d=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{ACCENT,blend(ACCENT,Color.WHITE,.10f)});d.setCornerRadius(dp(c,15));}else d=round(SURFACE_2,15,BORDER,1,c);b.setBackground(d);pressMotion(b,c);return b;'
u=u.replace(old,new)
old='v.setBackground(round(SURFACE,20,BORDER,1,c));return v;'
new='GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.TL_BR,new int[]{blend(SURFACE,SURFACE_2,.32f),SURFACE});d.setCornerRadius(dp(c,20));d.setStroke(dp(c,1),BORDER);v.setBackground(d);return v;'
u=u.replace(old,new)
if 'static int blend(' not in u:
    u=u.replace('static int withAlpha(int color,int alpha){return Color.argb(alpha,Color.red(color),Color.green(color),Color.blue(color));}', 'static int withAlpha(int color,int alpha){return Color.argb(alpha,Color.red(color),Color.green(color),Color.blue(color));}\n    static int blend(int a,int b,float t){t=Math.max(0f,Math.min(1f,t));return Color.rgb((int)(Color.red(a)*(1-t)+Color.red(b)*t),(int)(Color.green(a)*(1-t)+Color.green(b)*t),(int)(Color.blue(a)*(1-t)+Color.blue(b)*t));}')
p.write_text(u)
print('patched 1.6.1')
